---
- name: Install Apache on systems with Nginx running
  hosts: all
  become: true
  vars:
    apache_port: 8081

  tasks:
    - name: Detect OS family
      ansible.builtin.debug:
        msg: "Running on {{ ansible_os_family }}"

    - name: Install Apache on Debian/Ubuntu
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache on RHEL/CentOS
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure Apache listens on custom port (8081)
      ansible.builtin.lineinfile:
        path: "{{ '/etc/apache2/ports.conf' if ansible_os_family == 'Debian' else '/etc/httpd/conf/httpd.conf' }}"
        regexp: '^Listen'
        line: "Listen {{ apache_port }}"
        backup: yes

    - name: Update default VirtualHost for Debian/Ubuntu
      ansible.builtin.replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '(<VirtualHost\s+\*:)\d+>'
        replace: '\g<1>{{ apache_port }}>'

      when: ansible_os_family == "Debian"

    - name: Update default VirtualHost for RHEL/CentOS
      ansible.builtin.replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '(<VirtualHost\s+\*:)\d+>'
        replace: '\g<1>{{ apache_port }}>'
      when: ansible_os_family == "RedHat"

    - name: Copy updated HTML file
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{ '/var/www/html/index.html' }}"
        owner: root
        group: root
        mode: '0644'

    - name: Restart Apache service
      ansible.builtin.service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: restarted

