---
- name: Update Apache HTML page
  hosts: all
  become: yes
  vars:
    apache_docroot: /var/www/html
    html_source: /home/ansible/apache-update/playbooks/files/index.html
    apache_port: 8080
  tasks:
    - name: Ensure Apache is installed
      ansible.builtin.package:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Apache is started and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

      - name: Ensure Apache listens on port {{ apache_port }}
      replace:
        path: /etc/apache2/ports.conf
        regexp: '^Listen\s+\d+'
        replace: "Listen {{ apache_port }}"
      notify: restart apache

    - name: Update Apache VirtualHost port
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '<VirtualHost \*:.*>'
        replace: "<VirtualHost *:{{ apache_port }}>"
      notify: restart apache

    - name: Copy updated HTML page
      copy:
        src: "{{ html_source }}"
        dest: "{{ apache_docroot }}/index.html"
        owner: www-data
        group: www-data
        mode: '0644'
      notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
        enabled: yes
